mozilla/python_mozetl

tests/test_main.py

The default tests fail to run due to multiple spark contexts. This uses the consolidated SparkSession object from Spark 2.0 and creates a shared spark context.

Use SparkSession instead of SparkContext

---

mozetl/testpilot/containers.py
tests/test_containers.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/20)

Add 'pageRequestCount' to containers ETL job

---

mozetl/tab_spinner/generate_counts.py
mozetl/tab_spinner/utils.py
scheduling/tab_spinner.py
tests/tab_spinner_ping.json
tests/test_tab_spinner_aggregates.py

Original ETL notebook here: https://gist.github.com/fbertsch/f08998b87174d73c6f939b911e2cce53
I may not be using this library correctly. Feel free to request significant changes :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/15)

Bug 1358661 - Add tab spinner etl job

---

scheduling/tab_spinner.py

I am not a smart man.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/25)

Use correct tab_spinner function in scheduling script

---

mozetl/topline/historical_backfill.py
tests/test_topline_historical_backfill.py

This makes it possible to batch import executive report data. This has the possibility of overwriting the entire repository, so a confirmation is needed to continue.
This has been used to import both weekly and monthly data to `net-mozaws-prod-us-west-2-pipeline-analysis/amiyaguchi/topline_summary`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/26)

Add batch and overwrite options to historical backfill

---

mozetl/tab_spinner/generate_counts.py

Tested, works, and data appears on the dash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/29)

Tab Spinner - Upload files after running ETL

---

mozetl/churn/churn.py
tests/test_churn.py

Split several more country codes out of "Rest of World".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/30)

Bug 1363841 - Add more countries

---

mozetl/search/daily_search_rollups.py

[Bug 1364530](https://bugzilla.mozilla.org/show_bug.cgi?id=1364530)
This adds the python version of the daily search rollup notebook. This does some slight reformatting and adds a new entrypoint using click.
Tests have been omitted, since the purpose of this PR is to move the job into a repository,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/35)

Bug 1364530 - Add daily search rollups via nbconvert

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/42)

Update README with test & scheduling instructions

---

mozetl/search/daily_search_rollups.py

I am still figuring out how we can test this on real data without causing a failure when the airflow job runs.
https://bugzilla.mozilla.org/show_bug.cgi?id=1368089
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/48)

Filter followon searches from search daily job

---

mozetl/maudau/maudau.py
tests/test_maudau.py
tests/test_pulse.py

In addition to the unit tests I ran against main_summary and it matched the results of the existing notebook.

Bug 1370522 - Port official engagement ratio heuristic to this repo

---

.travis.yml
Dockerfile
README.md
mozetl/search/search_rollups.py
runtests.sh
setup.py
tests/conftest.py
tests/test_search_rollup.py
tests/test_utils.py
tox.ini

[Bug 1376808 - Package python_mozetl test infrastructure in docker](https://bugzilla.mozilla.org/show_bug.cgi?id=1376808)
Resolves issue #45 and #46. This should simplify the setup for running tests in `mozetl`. 
Travis might fail because flake8 is actually running now.

Bug 1376808 - Package python_mozetl test infrastructure in docker

---

mozetl/maudau/maudau.py
mozetl/utils.py

Per issue #67. Spinning up a cluster to test.

apply ACL headers to S3 transfer

---

mozetl/search/dashboard.py
tests/conftest.py
tests/test_search_dashboard.py

[Example notebook](https://github.com/mozilla/search-adhoc-analysis/blob/master/search-dashboard/search_dataset_test.ipynb)

Add basic ETL job for search dashboard dataset

---

bin/mozetl-submit.sh

https://bugzilla.mozilla.org/show_bug.cgi?id=1388869

Bug 1388869 - Install and build package separately on submission

---

mozetl/shield/privacy_prefs.py

Is this all I need to do to make the ETL job create the new table with the new schema?

bug 1387236: use v2 of schema

---

mozetl/cli.py
mozetl/search/search_rollups.py
tests/test_search_rollup.py

Bug 1365580 - Add search_rollups to the cli

---

mozetl/taar/taar_locale.py
tests/test_taar_locale.py

AMO will only report compatible, public add-ons. OS widgets and other unlisted/unapproved add-ons are not reported and will filter the recommendation list.

Restrict the recommended add-ons to the ones in AMO for taar_locale

---

mozetl/search/search_rollups.py
tests/test_search_rollup.py

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1402106)

Bug 1402106 - Align monthly search_rollup to beginning of month

---

mozetl/clientsdaily/fields.py
mozetl/clientsdaily/rollup.py
tests/test_clientsdaily.py

A few tweaks to make this code runnable via Airflow. In particular, the "Avoid using spark sql functions too early" commit is needed.

Bug 1401655 - Clean up clients-daily job

---

mozetl/experimentsdaily/rollup.py

We need to avoid manipulating Spark SQL functions before setting up the Spark context, and I removed a few unused arguments.

Clean up experimentsdaily code to run via Airflow.

---

mozetl/clientsdaily/fields.py

Add shutdown_kill aggregate

---

mozetl/sync/bookmark_validation.py
tests/test_sync_bookmark.py

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1409219)
@kitcambridge r?

Bug 1409219 - snakecase columns when using sync_summary_v2

---

mozetl/search/experiments.py

(distribution id and app version)

Bump version for new columns

---

mozetl/clientsdaily/fields.py
tests/test_clientsdaily.py

Request from :joy on IRC.
Also clean up the tests a bit.

Add "mean" for unique domains

---

mozetl/search/dashboard.py
tests/test_search_dashboard.py

If this looks good, I'll backfill the data and hotswap tomorrow.

Add search_cohort and locale to search_aggregates

---

mozetl/cli.py
mozetl/engagement/churn_to_csv/job.py

This adds a minimal set of changes to convert the notebook into a module in python_mozetl.
The job is on life support, so I'd like to avoid making too many changes to the job.

Bug 1355990 - Port churn_to_csv to mozetl

---

.gitignore
mozetl/taar/taar_dynamo.py

I've reworked the data loader as per @sunahsuh comments that everything should just be in one large script.
The `spark-submit` command I use to invoke this on the ATMO cluster is included in the comments at the top of the module.
I'm really not sure how to integrate this with the rest of airflow though.  I don't know how to use the DAG stuff at all.

init checkin of a Dynamo loader for TAAR

---

mozetl/cli.py

@sunahsuh this should resolve https://bugzilla.mozilla.org/show_bug.cgi?id=1442983

Register a new command `taar_dynamo`

---

mozetl/search/aggregates.py

Hey Harter, curious what you think about this. I had some difficulty understanding the flow of code before and I think this clarifies things a bit.

Unroll code to generate search aggregates somewhat

---

mozetl/cli.py
mozetl/taar/taar_amowhitelist.py
mozetl/taar/taar_utils.py
tests/test_taar_amowhitelist.py
tests/test_taar_utils.py

This adds a new taar_amowhitelist command to fetch the AMO database dump in taar_amodump, filter it down and upload a AMO addon whitelist.

Adds a new taar_amowhitelist command and ETL job to mozetl

---

.travis.yml
mozetl/cli.py
mozetl/engagement/churn_to_csv/job.py
mozetl/taar/taar_amodump.py
mozetl/taar/taar_amowhitelist.py
mozetl/taar/taar_dynamo.py
setup.py
tests/test_taar_amowhitelist.py

Enforce flake8 on CI and fix formatting

---

mozetl/taar/taar_utils.py

This should fix issue #219 by adding a temporary directory that self destructs when invoking the `mozetl.taar.taar_utils.store_json_to_s3` function.

store_json_to_s3 was not using a temporary directory before uploading

---

mozetl/cli.py
mozetl/maudau/maudau.py

This fixes issue #141, and is also related to [mozilla/telemetry-airflow #308](https://github.com/mozilla/telemetry-airflow/issues/308)

Fix #141 - Register maudau as engagement_ratio

---

mozetl/landfill/sampler.py
setup.py
tests/conftest.py
tests/test_landfill_sampler.py

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1464484)
This PR formalizes the landfill-sampler as a mozetl job. This job needs to be submitted via Databricks to utilize a specific IAM role due to inclusion of sensitive data. This job filters out all PII so that it can be used CI jobs.

Bug 1464484 - Add landfill sampler to mozetl

---

mozetl/cli.py

This adds an existing job to the CLI. I forgot to add this into the main PR for that job.

Add landfill_sampler to the cli

---

mozetl/hardware_report/hardware_dashboard.py

This will enable rerunning of historical hardware reports. This has been tested in telemetry-test-bucket.
At this point I'm not even sure who to tag as reviewer here... tag @acmiyaguchi

Make hardware report idempotent

---

mozetl/taar/taar_lite_guidguid.py

We no longer need to do this given new whitelisting approach

Fixes: #236

---

mozetl/taar/taar_similarity.py
tests/test_taar_similarity.py

This is just a reformatting PR before making changes to the similarity job to use clients_daily instead of longitudinal

reformatted code with black

---

mozetl/taar/taar_amowhitelist.py
tests/test_taar_amowhitelist.py

Added tests around featured addon extraction
Added test to verify that OS platform is encoded in JSON output

Refactor the whitelist generation to use accumulator classes

---

setup.py

If this fixes the problem, I'll pin them all.

Pin moto test dep

---

mozetl/taar/taar_similarity.py
mozetl/utils.py

This is allows for writing jobs compatible with both EMR and Databricks.

Add util for safe session stopping on Databricks

---

mozetl/utils.py
tests/test_utils.py

This fixes a fix for safe session stopping util (condition was reversed).

fixup! Add util for safe session stopping on Databricks

---

mozetl/addon_aggregates/addon_aggregates.py

This removes the fetch for test pilots experiments. We'll now treat any installed test-pilot add-ons as "self-installs", which won't impact the key dashboards in a major way as demonstrated in this notebook: 
https://dbc-caf9527b-e073.cloud.databricks.com/#notebook/70038/command/70068
I've also removed the `DEFAULT_THEME_ID` constant, since it was unused.

Remove test-pilot filtering

---

mozetl/search/aggregates.py

This should help us schedule/run this etl code from databricks

Use stop session safely helper in search aggregates datasets

---

mozetl/search/aggregates.py
tests/test_search_aggregates.py

@harterrt could you tell me if this is on the right track? Basically I try to coerce the ad click counts into a similar format as the search_counts data in a seperate dataframe, then perform a union onto the main dataset. It *seems* to work, though this is pushing the limits of my pyspark knowledge/acumen.
If this looks ok, I'll parametrize this logic and also add a similar transformation for `scalar_parent_browser_search_with_ads`

Bug 1519233 - Add ad click counts to search datasets

---

bin/mozetl-submit-dataproc.sh
mozetl/graphics/create_dashboard_job.sh
mozetl/graphics/create_trends_job.sh
mozetl/symbolication/create_cluster.sh
mozetl/symbolication/modules_with_missing_symbols.py
mozetl/symbolication/top_signatures_correlations.py

CI isn't fixed yet.
Goes with https://github.com/mozilla/telemetry-airflow/pull/1205
notebooks:
https://dbc-caf9527b-e073.cloud.databricks.com/#workspace/Users%2Fmcastelluccio%40mozilla.com%2Fmodules-with-missing-symbols
https://dbc-caf9527b-e073.cloud.databricks.com/#workspace/Users%2Fmcastelluccio%40mozilla.com%2Ftop-signatures-correlations

Port symbolication jobs from databricks

---

mozetl/symbolication/modules_with_missing_symbols.py
mozetl/symbolication/top_signatures_correlations.py

I thought sunday was 0 as it should be

Mod 7 weekday arg in symbolication jobs

---

mozetl/graphics/graphics_telemetry_dashboard.py
mozetl/graphics/graphics_telemetry_trends.py

Changes to use mozdata for analysis tables.  I'll make a pr to them shim code as well for completeness

Change graphics jobs to use mozdata for temp tables

---

mozetl/symbolication/top_signatures_correlations.py

Generate correlations for the top 300 signatures instead of top 200

---

mozetl/bhr_collection/bhr_collection.py

This PR outputs hang annotation information which we are currently largely discarding from the bhr ping. This will be used to display additional hang information in the portal located at https://fqueze.github.io/hang-stats

output hang annotation information in the bhr job

---

mozetl/graphics/graphics_telemetry_dashboard.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1694448#c4
If this is all it takes to fix then probably should have done this sooner

Fix error on missing media decoders in graphics job

---

docs/conf.py
mozetl/graphics/graphics_telemetry_dashboard.py
tox.ini

Background:
https://bugzilla.mozilla.org/show_bug.cgi?id=1737588

Also catching TypeError in graphics_telemetry_dashboard.py 

---

mozetl/graphics/create_cluster.sh
setup.py

bug(1809624): tweaked package requirements to use git for installing the moztelemetry package

---

mozetl/bhr_collection/bhr_collection.py
mozetl/bhr_collection/create_cluster.sh

Compared with the PRs created by Eduardo on another migration project. I realized that 
1. the Google Cloud storage package is missing in the .sh file. 
2. The test bucket details

Add metadata to bhr_collection and point to test gcs env

---

mozetl/bhr_collection/bhr_collection.py

@BenWu 
I think we could also do with reducing the sampling - if my memory serves, there's a good chance this is still going to OOM without reducing it.

Parameterize bhr thread filtering
