- .travis.yml
- setup.py
- tox.ini
This should let this repository be run under continuous integration using travis and codecov.io. I've tested this against my `churn-port` branch. 
This uses tox for setting up the environment and test-runner. As long as you have your `PYTHONPATH` set correctly with the pyspark and py4j dependencies, you should be able to run `tox` to run tests.
Alternatively, you can run pytest directly if you want more flexibility. The dependencies for pytest are in setup.py for setting up your own virtualenv.
> Add .travis.yml and tox.ini for automated testing

- .gitignore
- python_etl/basic_etl/__init__.py
- python_etl/basic_etl/transform.py
- python_etl/testpilot/containers.py
- python_etl/testpilot/pulse.py
- python_etl/testpilot/utils.py
- tests/pulse_ping.json
- tests/test_containers.py
- tests/test_main.py
- tests/test_pulse.py
- tests/utils.py
These jobs are currently running on ATMO. We'd like to get these jobs
reviewed and running on Airflow.
basic_etl was previously in it's own repository
[here](https://github.com/harterrt/betl) but will now be maintained in
this repository.
> Add testpilot ETL jobs and basic_etl library

- scheduling/pulse.py
This allows us to schedule the job from Airflow. Later today I plan on
moving this code into the package and generalizing with a click CLI
wrapper.
> Add simple wrapper to pulse etl job

- MANIFEST.in
- mozetl/topline/schema.py
- setup.py
This makes it possible to pass in `--py-files=dist/*.egg` to `spark-submit`.
This fixes issues involved with deployment via `bdist_egg`. Json files do not get distributed by default. This also changes relative paths to static assets to using package resources instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/24)
> Fixes #22 - Add static files to setup.py

- mozetl/topline/topline_dashboard.py
- mozetl/utils.py
- tests/test_topline_dashboard.py
- tests/test_utils.py
There are certain permission issues when deploying topline_dashboard due to permission errors with the spark executor. One alternative is to write the csv files to hdfs and copy over to local disk. This is not necessarily an elegant solution to the problem, so the tried solution is to use the collect (as long as this dataset stays within the size of the driver).
This patch works in practice, and was used to generate reports under `net-mozaws-prod-us-west-2-pipeline-analysis/amiyaguchi/topline-dashboard-data/`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/27)
> Bug 1357875 - Use toLocalIterator instead of writing directly to `file://` via spark

- mozetl/testpilot/txp_mau_dau.py
This ports over the TxP Mau Dau job from a python notebook to a python script so we can schedule it with airflow.
In the process of porting, however, I also made some significant modifications to the format and process, simplifying both. As I mentioned in [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1361186), I think this level of change might warrant writing to a different location and allowing query owners to move over their queries one by one.
I realize I have no tests -- they'd be a nice-to-have, but I don't think this job warrants that effort at the moment.
cc @ilanasegall
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/28)
> Bug 1361186: Port TxP Mau Dau job from ipynb

- mozetl/utils.py
Materializing the dataframe/rdd can take a while, which often causes
toLocalIterator to timeout. [1] This is solved on newer versions of
pyspark, but can be worked around by caching and materializing the
dataframe before calling toLocalIterator.
[1] https://issues.apache.org/jira/browse/SPARK-18281
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/32)
> Cache and materialize a dataframe before writing to disk

- tests/test_topline_dashboard.py
- tox.ini
The update to mock 1.0.0 introduces a missing dependency, but also fixes
an older issue of mock not interacting well with pyspark. This removes
monkeypatching for older tests.
PR #32 should be addressed to fix tests that are failing due to a lack of rdd materialization in this pull request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/36)
> Fix issue #34 caused by missing mock dependency

- mozetl/utils.py
toLocalIterator causes intermittent issues because rdd materialization
is variable. Collect is more consistent at the cost of not being limited
to dataframes that can fit into driver memory.
This will spare headaches in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/37)
> Use collect instead of toLocalIterator for write_csv

- mozetl/churn/churn.py
Bumping the version for `main_summary` in churn.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/41)
> Bump main_summary to v4 in churn

- mozetl/testpilot/containers.py
The ETL job takes a few parameters that were dropped with the most recent revision:
https://github.com/mozilla/python_mozetl/blob/master/mozetl/testpilot/utils.py#L6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/python_mozetl/47)
> Pass arguments to containers testpilot etl job

- .travis.yml
- mozetl/topline/topline_dashboard.py
- mozetl/utils.py
- tests/conftest.py
- tests/test_churn.py
- tests/test_topline_dashboard.py
- tests/test_topline_historical_backfill.py
- tests/test_utils.py
This addresses issue #21 among other things.
* Bump spark from 2.0.0 to 2.0.2
* Refactor spark session object into conftest.py
* Add `dataframe_factory` fixture for generating testing datasets from python dictionaries and fragments
* Refactor various tests to use `dataframe_factory`, generally using a helper function fixture that partially applies the base sample of the data and optionally the schema for the dataframe
* Add and test `utils.write_csv_to_s3`
> Refactor tests and add utility function for uploading csv to s3

- mozetl/topline/topline_summary.py
- tests/conftest.py
- tests/test_topline_summary.py
[Bug 1375725](https://bugzilla.mozilla.org/show_bug.cgi?id=1375725)
The ToplineSummaryView is difficult to validate. I rewrote the job in pyspark -- the job was originally ported from python to scala because of regex performance with spark UDFs. The job can use pure dataframe constructs, preventing processing bottlenecks.
A bonus is that python_mozetl is easy to use as a library in jupyter (and presumably zeppelin). This has made validating the results of this job nicer to work with.
> Bug 1375725 - Port ToplineSummaryView to python_mozetl

- mozetl/topline/topline_summary.py
```
INFO:mozetl.topline.topline_summary:Loading main_summary into memory...
INFO:mozetl.topline.topline_summary:Running the topline summary...
INFO:mozetl.topline.topline_summary:Saving rollup to disk...
INFO:mozetl.topline.topline_summary:Writing topline summary to s3://telemetry-parquet/topline_summary/v1/v1/mode=weekly/report_start=20170618
Traceback (most recent call last):
File "/mnt/analyses/python_mozetl/run.py", line 1, in <module>
from mozetl.topline import topline_summary as ts; ts.main()
File "/mnt/anaconda2/lib/python2.7/site-packages/click/core.py", line 716, in __call__
return self.main(*args, **kwargs)
File "/mnt/anaconda2/lib/python2.7/site-packages/click/core.py", line 696, in main
rv = self.invoke(ctx)
File "/mnt/anaconda2/lib/python2.7/site-packages/click/core.py", line …
```
> Set topline_summary mode to "overwrite"

- mozetl/topline/topline_summary.py
- tests/test_topline_summary.py
Resolves [Bug 1377730 - Weekly Topline Summary aborts on save](https://bugzilla.mozilla.org/show_bug.cgi?id=1377730)
`document_id` deduplication causes a large data shuffle across a week of data (1+TB of main_summary), running the cluster 2 hours before failing. Disabling deduplication makes the job work again.
> Bug 1377730 - disable document_id deduplication in topline_summary

- mozetl/churn/churn.py
- tests/test_churn.py
As part of the change at [1], all the engagement scalars were
renamed to conform to the general "scalar" convention. Update
the churn code accordingly.
[1] https://github.com/mozilla/telemetry-batch-view/commit/b7313c3e51a5d56b7ca597569e74d75088a13ff2
> Bug 1378899 - Rename engagement fields

- mozetl/churn/churn.py
- tests/test_churn.py
[Bug 1378989 - Churn job from mozetl should retry on exceptions](https://bugzilla.mozilla.org/show_bug.cgi?id=1378989)
This should prevent the exception handler from suppressing the error. This behavior caused the churn job to miss data for several weeks.
> Bug 1378989 - remove catching of exceptions in churn job

- mozetl/constants.py
- mozetl/search/search_rollups.py
- mozetl/topline/topline_summary.py
- tests/test_search_rollup.py
- tests/test_topline_summary.py
In-content searches were removed from the search rollup in a refactor, causing
search data to become skewed. This also affects the topline summary, inflating
the search results significantly.
> Bug 1368089 - Filter incontent searches in search aggregation jobs

- mozetl/constants.py
Should this be enough to track the new search event?
This pull request should not land until [a matching patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1381460) on the Firefox side to add the event in telemetry gets r+. In order to make sure the event name won't change.
> Bug 1381460 - Whitelist activity stream event source

- mozetl/shield/privacy_prefs.py
- tests/test_shield_privacy_prefs.py
`included_shield_pings` was throwing an error because payload/payload/study wasn't included in the filtered ping. This PR fixes this error by adding the field to the dataframe config.
> Fix tests for shield privacy ETL

- mozetl/testpilot/txp_mau_dau.py
- tests/resources/txp_experiments.json
- tests/test_txp_mau_dau.py
- tests/utils.py
The "Send" experiment doesn't use an addon at all, which broke an assumption in the txp_mau_dau job. Adds test for this case and the public testpilot `experiments.json` file as a fixture.
> Fix txp_mau_dau job for case where the experiment doesn't have an addon

- mozetl/shield/privacy_prefs.py
This makes the job recognize the shield pings. We still have the problem where fields are not showing up in the raw pings.
> Make privacy prefs filter pings properly

- mozetl/shield/privacy_prefs.py
This function should be exposed without being wrapped in another
function.
> Fix shield privacy_prefs `etl_job` function

- mozetl/shield/privacy_prefs.py
- tests/test_shield_privacy_prefs.py
I want to measure the % of users who submit 1+ "page-problem" pings. But we only have data for the 'page-problem|page-works|breakage|notes|disable' pings. So, we don't know how many users are running the study who have never sent a page problem/works report.
This PR adds `study_state` extraction and load into the table, so I can get the total # of clients running the study add-on - including the ones who have not sent any breakage reports at all.
> bug 1387236: extract and load study_state too

- mozetl/clientsdaily/fields.py
- mozetl/clientsdaily/rollup.py
- tests/test_clientsdaily.py
Work for bug 1381896:
1) Repartitions before writing Parquet files and skips _SUCCESS flag for redash compatibility.
2) Adds dimensions: profile_age_in_days, sessions_started_on_this_day.
3) Casts profile_creation_date to a date object.
> add several dimensions and write more efficiently

- mozetl/cli.py
- mozetl/taar/taar_locale.py
- tests/test_taar_locale.py
This PR adds a new Python job that builds a list of top addons per locale to use in the TAAR project.
Please do not review this just yet, I'm mainly opening the PR as I want to get tests running here (having problems locally).
> Add the TAAR job to get locale-based recommendations

- mozetl/clientsdaily/fields.py
- mozetl/clientsdaily/rollup.py
- tests/test_clientsdaily.py
Per bug 1381896, convert main to run daywise rather than monthwise. Also add columns that tally searches for each chrome access point.
> Bug 1381896 - add daywise rollups and search counts per access point

- mozetl/cli.py
- mozetl/taar/taar_locale.py
- mozetl/taar/taar_similarity.py
- mozetl/taar/taar_utils.py
- setup.py
- tests/test_taar_locale.py
- tests/test_taar_similarity.py
- tests/test_taar_utils.py
This job is used to compute TAAR similarity-based addon donor list.
This job clusters users into different groups based on their active addons. A representative users sample is selected from each cluster ("donors") and is saved to a model file along with a feature vector that will be used, by the TAAR library module, to perform recommendations.
*Please do not review yet*
> Taar similarity job

- mozetl/taar/taar_similarity.py
- tests/test_taar_similarity.py
Without this fix, the job will fail on Spark 2.2.0 due to [a bug](https://issues.apache.org/jira/browse/SPARK-20803) in the Kernel Density Estimation not correctly handling Numpy types. Moreover, the job will go OOM on previous Spark versions due to other bugs, so we can't really use anything less than Spark 2.2.0.
This fix was tested on EMR 5.8.0 and the results are accessible in the test telemetry bucket under the TAAR directory
> Make the similarity job work around SPARK-20803

- mozetl/cli.py
Add two more entrypoints so we can easily run `clientsdaily` and `experimentsdaily` via Airflow.
I also updated `cli.py` so that it would call its entrypoint if invoked directly. This allows one to test out the cli via:
` $ python mozetl/cli.py --help`
And get useful output.
> Bug 1401655 - Add cli entry point for clients/experiments daily

- mozetl/cli.py
- mozetl/clientsdaily/rollup.py
- mozetl/experimentsdaily/rollup.py
In particular, change the `clientsdaily` job to accept an "end" date
instead of a "start" date to simplify the airflow side. Also accept
the LAG specification as an argument.
> Bug 1401655 - Prepare jobs to run via Airflow.

- mozetl/churn/churn.py
- tests/churn/test_churn.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1403745)
The schema types are validated through the test suite.   
This is the source of the failing `churn_to_csv` job today. The acquisition_date field was a `date` type instead of a `yyyy-MM-dd` `string` type.
> Bug 1403745 - Validate churn schema via test suite

- mozetl/churn/churn.py
- mozetl/churn/schema.py
- tests/churn/test_churn.py
- tests/conftest.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1389231)
This adds the `new-profile` ping as a data source for churn. A new
column `is_new_profile` differentiates the source for the clients.
This is also a version bump to `v3`.
Additionally, `spark.sql.session.timeZone` is set to UTC, which require
Spark 2.2.0 to work (see SPARK-18936 for details). The spark session
assumes the timezone of the local machine, which can cause failing
tests.
> Bug 1389231 - Add new-profile ping to churn

- mozetl/clientsdaily/rollup.py
- mozetl/experimentsdaily/rollup.py
In keeping with all the other datasets.
> Use underscore instead of hyphen in dataset names.

- tests/test_pulse.py
Fixes issue #151. 
This test has been failing after an update to some mysterious dependency. It seems that the test expects the wrong value after further inspection. Both [`consoleErrors`](https://github.com/mozilla/python_mozetl/blob/master/tests/pulse_ping.json#L59) and [`trackingProtection`](https://github.com/mozilla/python_mozetl/blob/master/tests/pulse_ping.json#L74) have non-null values in the pre-transform stage, however the test expects null values for some reason.
> Fixes #151 - Fix expected value in `test_pulse.py`

- mozetl/engagement/retention/job.py
This appears as the literal `app_version` pre-2.2.
> Bug 1410254 - Fix app_version

- mozetl/clientsdaily/fields.py
- tests/test_clientsdaily.py
- tests/test_taar_legacy.py
I can't imagine a case where a null would be preferred over the first non-null value, particularly given that the data is not sorted first, as far as I can tell.
> Bug 1416225 - skip nulls with "first" aggregation in clients_daily

- mozetl/search/search_rollups.py
- tests/test_search_rollup.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1393227)
The manifest files are an extra layer of indirection that can safely be
removed. This simplifies the rollup script.
> Bug 1393227 - Remove search rollup manifest files

- mozetl/engagement/churn/job.py
- tests/engagement/test_churn.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1419080)
Attribution is [often] missing from main-pings. This uses the attribution value from the new-profile ping over the main-ping value when generating churn and retention.
The left join will most likely increase the processing time on this dataset.
> Bug 1419080 - Use attribution from new-profile pings in churn 

- mozetl/basic/transform.py
Bare except makes it harder to interrupt programs. Better to catch the Exception
class instead, which will at least let the SystemExit and KeyboardInterrupt
exceptions go through (https://stackoverflow.com/a/14797463).
> Fix use of bare except in basic transforms

- mozetl/addon_aggregates/addon_aggregates.py
- mozetl/cli.py
- tests/test_addon_aggregates.py
Added logic to only record `first_addon_install_date` for self-installed add-ons, otherwise it should be `null`. This was an oversight from the initial script, and I'd like to backfill through 2017-10-01.
r? @acmiyaguchi
> Fix min install date

- mozetl/taar/taar_dynamo.py
This parses the date option passed into taar_dynamo into a proper python datetime object. 
I've tested this patch on atmo using `mozetl-submit.sh` patched to point at crankycoder/python_mozetl instead of mozilla/python_mozetl
r? @sunahsuh
> Parse the date string into a proper date object in taar_dynamo.

- mozetl/search/aggregates.py
- tests/test_search_aggregates.py
SCD is proving to be uncomfortably big for re:dash. Filtering by sample_id will make quick calculations easier.
> Partition search_clients_daily by sample_id

- mozetl/search/aggregates.py
- tests/test_search_aggregates.py
`tagged-sap` and `tagged-follow-on` both contain hyphens, which makes them difficult to work with in Presto. Adding convenience columns which replace the hyphens with underscores.
This will close out the changes to scd_v2
> Add convenience columns to search tables

- mozetl/search/aggregates.py
As is, line 265 throws an error because python expects to pass `bucket`
and `prefix` variables to `search_aggregates_etl` and
`search_clients_daily_etl`.
Unfortunately, we don't have test coverage for the cli command.
I had to run this manually to test.
> Search bugfix: Use consistent variable names

- mozetl/taar/taar_amodump.py
This reworks the taar_amodump job to run completely in memory and not write any temporary files to disk.
cc/ @acmiyaguchi
> Reworked the AMO Dump to run completely in memory

- mozetl/taar/taar_amowhitelist.py
- mozetl/taar/taar_lite_guidguid.py
This addresses https://github.com/mozilla/taar-lite/issues/9
TAARlite should not whitelist the Firefox Pioneer addon, and it should not consider the Firefox Pioneer add-on when querying for add-on suggestions.
cc/ @mlopatka
> Explicitly exclude 'Firefox Pioneer' addon from TAARlite

- mozetl/taar/taar_amowhitelist.py
- mozetl/taar/taar_lite_guidguid.py
- tests/test_taar_amowhitelist.py
The TAAR addon whitelist was including legacy addons by mistake.  This filters the list further ensuring that an `is_webextension` flag exists and is true for each addon in the whitelist.
> Exclude legacy extensions in the AMO whitelist

- mozetl/sync/bookmark_validation.py
- tests/test_sync_bookmark.py
Hi! We're currently [testing](https://bugzilla.mozilla.org/show_bug.cgi?id=1456221) a new bookmarks engine in Nightly. It reports the same validation results as the current `bookmarks` engine, and we'd like to include them in the `bmk_validation_problems` and `bmk_total_per_day` views, so that we can compare corruption rates for the two.
@acmiyaguchi r?
> Include new bookmarks engine results in Sync validation views

- .circleci/config.yml
- setup.py
The `.tox` cache is not updated to reflect new dependencies in the setup and subsequently breaks tests. This removes the per-branch, per-workflow, and fallback cache and replaces it with the checksum of `setup.py`. Locally, I would run `tox -r` to rebuild the dependencies on issues. It only adds a a minute or two to download all the dependencies from pypi.
>  Bug 1485049 - Upgrade pyspark used in python_mozetl's test environment to 2.3

- mozetl/taar/taar_locale.py
- tests/test_taar_locale.py
This migrates the taar_locale job to use the clients_daily table from the deprecated longitudinal table.
> Ported taar_locale to use clients_daily instead of using longitudinal table

- .circleci/config.yml
- tox.ini
This PR is the first part of a series to add python 3 support to mozetl. This adds CI support for py27, py36, and black (using the `--check` option). 
See #282 for the final state.
> [part 1] Add python3 and black to CI

- mozetl/taar/taar_similarity.py
- tests/test_taar_similarity.py
This PR:
* limits clients' sample to 1 row per client from the last 90 days (configurable), fixes #280
* contains some performance and minor improvements (of which the most important is caching iteratively read datasets)
/cc @mlopatka @crankycoder
> Improve Taar similarity jobs performance, fix #280

- README.md
This adds some basic instructions for manually running jobs on both ATMO and Databricks using scripts in `bin`.
> Add instructions for manual execution of jobs

- mozetl/addon_aggregates/addon_aggregates.py
This is a quick fix for fetching test pilot experiments list.
Test pilot was retired making this function throw exception, this should be revisited with a proper fix.
> Fix test pilot experiments fetch

- setup.py
```
Traceback (most recent call last):
File "/tmp/tmp.JRoh7UGRIS/runner.py", line 1, in 
from mozetl import cli
File "build/bdist.linux-x86_64/egg/mozetl/__init__.py", line 1, in 
File "build/bdist.linux-x86_64/egg/mozetl/main.py", line 4, in 
File "/mnt/anaconda2/lib/python2.7/site-packages/moztelemetry/__init__.py", line 2, in 
from .spark import *
File "/mnt/anaconda2/lib/python2.7/site-packages/moztelemetry/spark.py", line 17, in 
from .histogram import Histogram
File "/mnt/anaconda2/lib/python2.7/site-packages/moztelemetry/histogram.py", line 12, in 
import pandas as pd
File "/mnt/anaconda2/lib/python2.7/site-packages/pandas/__init__.py", line 23, in 
from pandas.compat.numpy import *
File "/mnt/anaconda2/lib/python2.7/site-packages/pandas/compat/numpy/__init__.py", line 22, in …
```
> [hotfix!] Update dependencies for churn-v2

- mozetl/cli.py
- mozetl/tab_spinner/tab_spinner.py
This will let us use `mozetl-submit` inside airflow, which is quite
a bit cleaner.
> Add a minimal click command for the tab spinner etl job

- mozetl/tab_spinner/tab_spinner.py
We were passing the wrong type of spark object to the actual etl
code.
> Fix tab-spinner click command

- setup.py
Seems like v1.9.99 has an issue importing S3Transfer
> Pin boto dependencies

- setup.py
It seems like the implicit upgrade to pandas 0.24 broke the tab spinner severity job, due to
a compatibility mismatch between the executor and workers. Let's pin our pandas version
to the last known working version (0.23.4) and add a comment warning people about this
in case they want to add new things in the future (the dependencies were explicitly pinned before 
for this exact reason). See: https://bugzilla.mozilla.org/show_bug.cgi?id=1525022
> Pin pandas to 0.23.4

- mozetl/tab_spinner/generate_counts.py
We actually were eliminating these old pings from consideration already,
but not in an efficient way.
> Bug 1528363 - Only consider last 180 days (=6 months) for tab spinner job

- README.md
- bin/mozetl-databricks.py
- mozetl/cli.py
- mozetl/system_check.py
- tests/test_system_check.py
This updates the Databricks workflow for supporting external modules that follow the mozetl convention. The convention is as follows:
* The module uses the `click` library for defining a command-line interface
* All arguments use the `@click.option` decorator. Arguments that are required should use the `required=True` parameter.
- `click` will expose command-line arguments via environment variables
* The module has a top-level `cli` submodule such that `from my_module import cli` is a valid command
A module that adheres to these basic conventions can be scheduled via Airflow using standard tooling.
> Update `mozetl-databricks.py` for running external mozetl-compatible modules

- mozetl/tab_spinner/generate_counts.py
- mozetl/tab_spinner/tab_spinner.py
- tests/test_cli.py
- tests/test_tab_spinner_aggregates.py
This fixes two issues with the tab_spinner job. The first is a relative import error in the module. The second is a serialization error due to the existence of the `numpy.float64` type.
The first is referenced in mozilla/telemetry-airflow#441. I've added a test that should prevent import errors from occurring again in `test_cli.py`. To verify that the tab spinner job works, I've tested the entire command using the `click.CliRunner`. This also caught the import error, as well as a hidden serialization error:
```
E       AssertionError: assert -1 == 0
E        +  where -1 = <Result TypeError('unaffected           0.0\n0ms - 999ms          0.0\n1000ms - 2296ms      1.0\n2297ms - 5276ms      ...124ms - 27855ms    0.0\n27856ms - 63999ms    0.0\n64000ms+             0.0\ndtype: float64 is not …
```
> Fix tab_spinner job

- mozetl/landfill/sampler.py
- tests/test_landfill_sampler.py
Reverts mozilla/python_mozetl#320
A validation ping or schema is missing for this test, which should note that the content is actually a string. 
```
Job aborted due to stage failure: Task 29 in stage 1.0 failed 4 times, most recent failure: Lost task 29.3 in stage 1.0 (TID 187, 10.166.227.193, executor 0): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
File "/databricks/spark/python/pyspark/worker.py", line 262, in main
process()
File "/databricks/spark/python/pyspark/worker.py", line 257, in process
serializer.dump_stream(func(split_index, iterator), outfile)
File "/databricks/spark/python/pyspark/serializers.py", line 381, in dump_stream
vs = list(itertools.islice(iterator, batch))
File "/databricks/spark/python/pyspark/util.py", line 55, in wrapper …
```
> Revert "Add content-based version detection."

- mozetl/landfill/sampler.py
- tests/test_landfill_sampler.py
Extension of #320 updated in light of #322 - the `content` field should be a string and not an object.
> Add content-based version detection (reprise)

- bin/mozetl-databricks.py
- mozetl/cli.py
- mozetl/taar/taar_ensemble.py
- tests/test_taar_ensemble.py
This adds a TAAR ensemble job to python_mozetl.
Extensions have been made to `bin/mozetl-databricks.py` to provide support for :  
* using spot, spot with on demand fallback and on_demand instance types
* overriding the instance type to get more powerful instance types from AWS 
* autoscaling as an option instead of a fixed number of workers
* setting the bid price of nodes (defaulting to 100% of on demand)
* installing custom python libraries to the cluster
> Adds a TAAR ensemble job 

- mozetl/search/aggregates.py
- setup.py
- tests/test_search_aggregates.py
It didn't work correctly when aggregating across dimensions and was
unused. Best to just use search_clients_daily for this use case.
> Bug 1547777 - Remove client count hll column from search_aggregates

- mozetl/search/aggregates.py
I found an error when looking at the ad probes using search clients daily versus main_summary. There is an over-counting error when exploding those fields.
The error/fix can be more easily explored in this minimal reproduction:
https://dbc-caf9527b-e073.cloud.databricks.com/#notebook/141261/command/141311
@harterrt r?
> Fix overcounting error when exploding ad fields

- .circleci/config.yml
* CircleCI just upgraded to debian 10 (buster) which does not not support
OpenJDK 8.
> Pins the docker images to use debian 9 (stretch)

- mozetl/taar/taar_update_whitelist.py
- tests/test_taar_update_whitelist.py
The AMO whitelist URL is now requested with a 'recex=True' option added
to the end of the URL to restrict addons to only the recommended list
for TAAR recommendd addons now.
cc @muffinresearch
> TAAR whitelist uses recommended addons only now.

- mozetl/taar/taar_update_whitelist.py
The new recommended addon list from AMO is quite short (<90 addons), this relaxes that constraint.
> updated taar whitelist to allow for short recommended whitelists

- mozetl/taar/taar_update_whitelist.py
The default write path for our whitelist was set incorrectly.
> fixes the s3 write path for the recommended whitelist

- mozetl/taar/taar_lite_guidguid.py
- tests/test_taar_lite_guidguid.py
The longitudinal table was structured as a dictionary of addon_guid -> addon_metadata, but the clients_daily table models the active_addons as a list of just addon_metadata.
This patch fixes the extraction of addon data per client to reflect the clients_daily schema.
This patch also unrolls the `extract_telemetry` function from using any nested functions to aid clarity.
> Fixes extraction bug in the clients_daily port of taarlite_guidguid

- mozetl/tab_spinner/utils.py
We would consider something "unaffected" for a short duration if we had no "short" tab spinner histogram OR "long" tab spinner histograms. It should
actually be "no short AND no long".
> Fix undercounting of tab spinners

- mozetl/graphics/create_cluster.sh
- mozetl/graphics/create_dashboard_job.sh
- mozetl/graphics/create_trends_job.sh
- mozetl/graphics/graphics_telemetry_dashboard.py
- mozetl/graphics/graphics_telemetry_trends.py
- setup.py
Migration of graphics-telemetry-dashboard-big-query and graphics-telemetry-trends-big-query jobs from databricks.  Intention is to use this repo as storage for the python driver code for a dataproc pyspark job.  Associated airflow pr https://github.com/mozilla/telemetry-airflow/pull/1191
Code is mostly unchanged; this is using boto3 for s3 access and adds cli arguments
The notebooks:
https://dbc-caf9527b-e073.cloud.databricks.com/#notebook/239724
https://dbc-caf9527b-e073.cloud.databricks.com/#notebook/240233
circleci deploy keys for this repo were deleted so ci doesn't work but I don't think it's needed.
> Port graphics trends from databricks to dataproc

- mozetl/symbolication/modules_with_missing_symbols.py
Socorro switched stackwalkers last week and the new one emits a null
instead of an empty string for the module version. This fixes
`is_old_firefox_module` to work with null (which is None).
> bug 1746874: fix case where version is None

- .circleci/config.yml
https://mozilla-hub.atlassian.net/browse/DSRE-413
This PR updates the key that CircleCI will use to write to gh-pages branch.
r?
> Update CircleCI SSH Key DSRE-413

- mozetl/symbolication/top_signatures_correlations.py
We recently raised the number of signatures to look at to 1000 (PR #367), but this caused the container to run out of memory when working on correlations for the release channel.
This reverts back to the previous value of 300.
> Revert to 300 signatures for correlations (#368)

- mozetl/bhr_collection/bhr_collection.py
The bhr_collection job is currently failing because we are now
seeing a FUNC line in a breakpad file which omits a symbol. I'm
not entirely sure why we're seeing this, but I don't see any
problem with just letting it through annotated as an empty symbol.
> Allow empty symbols in breakpad files for BHR

- mozetl/symbolication/top_signatures_correlations.py
The top_signatures_correlations task is getting killed off for using too
much memory. This drops the top signatures we're looking at from 300 to
250 as a temporary attempt to get the job succeeding again.
I also did some "magic number" reduction so it reads better.
> bug 1774415: reduce top signatures to 250

- mozetl/symbolication/top_signatures_correlations.py
We're having memory issues and it looks like the total number of crash
reports for the top signatures is increasing over time. This drops the
number of top signatures we look at which will drop the number of crash
reports which should reduce the memory used back to a workable number.
> bug 1775444: drop top signatures from 250 to 200

- setup.py
Dependency update for CI fix.
`flake8` for the `lint` job - 4.0.0 because it pins `importlib` due to a breaking change which caused the `AttributeError: 'EntryPoints' object has no attribute 'get'` problem. 
`protobuf` for the tests - 3.20.3 because that's what's suggested in the warnings:
```
E   TypeError: Descriptors cannot not be created directly.
E   If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
E   If you cannot immediately regenerate your protos, some other possible workarounds are:
E    1. Downgrade the protobuf package to 3.20.x or lower.
E    2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
E   
E   More information: …
```
> Pin flake8 and protobuf to fix lint and py37 CI jobs

- mozetl/bhr_collection/bhr_collection.py
bhr_collection is accessing the public symbols AWS S3 bucket directly rather than going through the Mozilla Symbols Server and getting redirected. We're planning to migrate to GCP and after we migrate, there won't be any AWS S3 bucket.
This fixes bhr_collection so that it works with our current setup as well as the setup we'll have after the GCP migration.
Details: https://bugzilla.mozilla.org/show_bug.cgi?id=1831952
> update symbols server url

- .circleci/config.yml
Changed include:
- Updated docker image to `3.7.11`-stretch
- pinning tox version inside the CI pipeline (install_dependencies instructions)
- Updating stretch repositories to fix the not found error.
This fixed the CI errors we were seeing related to repositories not being found.
> fix(DENG-1146): fixing install dependencies ci step

- mozetl/bhr_collection/bhr_collection.py
TODO - 
1. The GCS bucket in this PR points to `moz-fx-data-static-websit-f7e0-analysis-output`. Need to find out the right bucket
2. Create a subsequent PR in `telemetry-airflow` to update the dag config and remove the gcs_sync task
> DENG 1022 - Update bhr_collection DAG to write to GCS instead of S3

- mozetl/graphics/graphics_telemetry_dashboard.py
- mozetl/graphics/graphics_telemetry_trends.py
- setup.py
Fixes: [DENG-1025](https://mozilla-hub.atlassian.net/jira/software/c/projects/DENG/boards/593?modal=detail&selectedIssue=DENG-1025) along with https://github.com/mozilla/telemetry-airflow/pull/1774
Configured with the test GCS bucket for now. Will update with prod bucket in case it works
> DENG-1025: gfx_telemetry r/w to GCS instead of S3

- mozetl/graphics/graphics_telemetry_dashboard.py
- mozetl/graphics/graphics_telemetry_trends.py
Follow-up of https://github.com/mozilla/python_mozetl/pull/388
Updating GCS bucket with prod name after testing with nonprod.
Will be merged along with https://github.com/mozilla/telemetry-airflow/pull/1777
> DENG-1025: gfx export to prod gcs bucket

- mozetl/symbolication/create_cluster.sh
- mozetl/symbolication/top_signatures_correlations.py
Along with https://github.com/mozilla/telemetry-airflow/pull/1829
This also removes the dependency on https://github.com/marco-c/crashcorrelations for storing result files in buckets.
Once I can confirm the files are written to the dev bucket I'll open another PR with the prod bucket name
> DENG-1023 crash_symbolication stores results on gcs instead of s3 (dev bucket for testing)

- mozetl/symbolication/top_signatures_correlations.py
The job worked in dev, so I'm updating the bucket with the prod one.
Note: last execution sent results to dev bucket, which I manually copied over to prod and tested by downloading some files from https://analysis-output.telemetry.mozilla.org
> DENG-1023 crash_symbolication stores results on gcs instead of s3 (prod)

- mozetl/bhr_collection/bhr_collection.py
The previous PR - https://github.com/mozilla/python_mozetl/pull/387 did not handle the `extra_args = {"ContentType": "application/json", "ContentEncoding": "gzip"}`. due to which the process was unable to read the files.
> Fix the bhr script to handle the extra arguements

- mozetl/bhr_collection/bhr_collection.py
The task of writing to gcs instead of s3 keeps is not working. 
The GCS bucket has been pointed to the test folder for testing purposes and will be reverted once the root cause of issue has been identified.
> Add dummy folder for testing BHR switch to gcs

- mozetl/symbolication/modules_with_missing_symbols.py
This adds the date in YYYY-mm-dd to the end of the email subject line so as to fix threading in the google groups interface.
This mirrors the change here: https://github.com/marco-c/missing_symbols/commit/2c3a1b4cc83e0012c5c18e0379f144d8533d9419
>  Add date in YYYY-mm-dd to end of email subject line

- mozetl/bhr_collection/bhr_collection.py
This PR just outputs an additional file containing hangs in child processes by piping through a config variable with the process name to filter on instead of hard-coding "Gecko."
> Output bhr hangs for child processes

- mozetl/graphics/graphics_telemetry_dashboard.py
The following commit in gecko-dev deprecated GRAPHICS_SANITY_TEST from `Histograms.json` which appears to have resulted in the ETL job using this python_mozetl logic to break as the result. We're expecting this code change to resolve this issue by the login no longer attempting to access the `GRAPHICS_SANITY_TEST` histogram.
> bug(1914369): remove GRAPHICS_SANITY_TEST* related code from graphics dashboard due to related deprecation in gecko-dev

- mozetl/graphics/graphics_telemetry_dashboard.py
This is a follow-up to the following change in the Histograms.json in gecko-dev:
https://github.com/mozilla/gecko-dev/commit/7f25ee929ca325e057bdfc256bb978954b5fed0d#diff-6c55b27a94376254370c09aa7b397a80d4b2f7c3cb28b690f33557e92f9f98b8
This change removed the following from the list of histograms to process:
- `PLUGIN_DRAWING_MODEL`
- `D3D11_COMPOSITING_FAILURE_ID`
- `OPENGL_COMPOSITING_FAILURE_ID`
> feat(bug-1917645): remove code related to PLUGIN_DRAWING_MODEL, D3D11_COMPOSITING_FAILURE_ID, and OPENGL_COMPOSITING_FAILURE_ID

- mozetl/bhr_collection/README.md
- mozetl/bhr_collection/bhr_collection.py
- mozetl/bhr_collection/create_cluster.sh
- mozetl/bhr_collection/requirements.txt
https://mozilla-hub.atlassian.net/browse/DENG-8305
More changes to this job are expected in the future so there are some updates to make this easier to run locally.  The main thing is updating the readme with instructions to setup dependencies and changing the sampling run in bigquery instead of on the client so only the sampled data is sent to the client.  Also removes AWS dependecies and code because they're not used anymore
> [DENG-8305] Make bhr_collection easier to run locally
